# Generated by Django 3.2.5 on 2021-08-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0001_initial'),
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='author_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projects'),
        ),
    ]
