# Generated by Django 3.2.5 on 2021-08-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0002_alter_issues_projet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='projet_id',
            new_name='project_id',
        ),
    ]
