# Generated by Django 3.2.5 on 2021-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('AMELIORATION', 'Amélioration'), ('TACHE', 'Tâche')], max_length=12)),
                ('priority', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Elevée')], max_length=7)),
                ('status', models.CharField(choices=[('A_FAIRE', 'A faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], max_length=8)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
